// <auto-generated />

using System;
using Encyclopedy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Encyclopedy1.Migrations
{
    [DbContext(typeof(EncyclopedyContext))]
    class EncyclopedyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Encyclopedy.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<int>("DisciplineId");

                    b.Property<string>("Intro");

                    b.Property<string>("Lasteditor");

                    b.Property<string>("Main");

                    b.Property<string>("Title");

                    b.Property<int?>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("Lasteditor");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Encyclopedy.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Branch");

                    b.Property<string>("Subbranch");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Encyclopedy.Edit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArticleId");

                    b.Property<DateTime>("EditDate");

                    b.Property<string>("Editable");

                    b.Property<string>("Oldtext");

                    b.Property<int>("Oldversion");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Edits");
                });

            modelBuilder.Entity("Encyclopedy.LoggedUser", b =>
                {
                    b.Property<string>("Login")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Editnum");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Surname");

                    b.HasKey("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Encyclopedy.Article", b =>
                {
                    b.HasOne("Encyclopedy.Discipline", "Discipline")
                        .WithMany("Articles")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Encyclopedy.LoggedUser", "LoggedUser")
                        .WithMany("Articles")
                        .HasForeignKey("Lasteditor");
                });

            modelBuilder.Entity("Encyclopedy.Edit", b =>
                {
                    b.HasOne("Encyclopedy.Article", "Article")
                        .WithMany("Edits")
                        .HasForeignKey("ArticleId");

                    b.HasOne("Encyclopedy.LoggedUser", "LoggedUser")
                        .WithMany("Edits")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
